/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as LembagaRouteImport } from './routes/lembaga'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as BukuIndexRouteImport } from './routes/buku.index'
import { Route as BukuPencarianRouteImport } from './routes/buku.pencarian'
import { Route as FiturSlugRouteImport } from './routes/fitur.$slug'
import { Route as BukuTahunIndexRouteImport } from './routes/buku.$tahun.index'
import { Route as BukuTahunBabRouteImport } from './routes/buku.$tahun.$bab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const LembagaRoute = LembagaRouteImport.update({
  id: '/lembaga',
  path: '/lembaga',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuIndexRoute = BukuIndexRouteImport.update({
  id: '/buku/',
  path: '/buku/',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuPencarianRoute = BukuPencarianRouteImport.update({
  id: '/buku/pencarian',
  path: '/buku/pencarian',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturSlugRoute = FiturSlugRouteImport.update({
  id: '/fitur/$slug',
  path: '/fitur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuTahunIndexRoute = BukuTahunIndexRouteImport.update({
  id: '/buku/$tahun/',
  path: '/buku/$tahun/',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuTahunBabRoute = BukuTahunBabRouteImport.update({
  id: '/buku/$tahun/$bab',
  path: '/buku/$tahun/$bab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/lembaga': typeof LembagaRoute
  '/profil': typeof ProfilRoute
  '/roadmap': typeof RoadmapRoute
  '/buku/pencarian': typeof BukuPencarianRoute
  '/fitur/$slug': typeof FiturSlugRoute
  '/buku/': typeof BukuIndexRoute
  '/buku/$tahun/$bab': typeof BukuTahunBabRoute
  '/buku/$tahun/': typeof BukuTahunIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/lembaga': typeof LembagaRoute
  '/profil': typeof ProfilRoute
  '/roadmap': typeof RoadmapRoute
  '/buku/pencarian': typeof BukuPencarianRoute
  '/fitur/$slug': typeof FiturSlugRoute
  '/buku': typeof BukuIndexRoute
  '/buku/$tahun/$bab': typeof BukuTahunBabRoute
  '/buku/$tahun': typeof BukuTahunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/lembaga': typeof LembagaRoute
  '/profil': typeof ProfilRoute
  '/roadmap': typeof RoadmapRoute
  '/buku/pencarian': typeof BukuPencarianRoute
  '/fitur/$slug': typeof FiturSlugRoute
  '/buku/': typeof BukuIndexRoute
  '/buku/$tahun/$bab': typeof BukuTahunBabRoute
  '/buku/$tahun/': typeof BukuTahunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hasil'
    | '/lembaga'
    | '/profil'
    | '/roadmap'
    | '/buku/pencarian'
    | '/fitur/$slug'
    | '/buku/'
    | '/buku/$tahun/$bab'
    | '/buku/$tahun/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hasil'
    | '/lembaga'
    | '/profil'
    | '/roadmap'
    | '/buku/pencarian'
    | '/fitur/$slug'
    | '/buku'
    | '/buku/$tahun/$bab'
    | '/buku/$tahun'
  id:
    | '__root__'
    | '/'
    | '/hasil'
    | '/lembaga'
    | '/profil'
    | '/roadmap'
    | '/buku/pencarian'
    | '/fitur/$slug'
    | '/buku/'
    | '/buku/$tahun/$bab'
    | '/buku/$tahun/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HasilRoute: typeof HasilRoute
  LembagaRoute: typeof LembagaRoute
  ProfilRoute: typeof ProfilRoute
  RoadmapRoute: typeof RoadmapRoute
  BukuPencarianRoute: typeof BukuPencarianRoute
  FiturSlugRoute: typeof FiturSlugRoute
  BukuIndexRoute: typeof BukuIndexRoute
  BukuTahunBabRoute: typeof BukuTahunBabRoute
  BukuTahunIndexRoute: typeof BukuTahunIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembaga': {
      id: '/lembaga'
      path: '/lembaga'
      fullPath: '/lembaga'
      preLoaderRoute: typeof LembagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/': {
      id: '/buku/'
      path: '/buku'
      fullPath: '/buku/'
      preLoaderRoute: typeof BukuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/pencarian': {
      id: '/buku/pencarian'
      path: '/buku/pencarian'
      fullPath: '/buku/pencarian'
      preLoaderRoute: typeof BukuPencarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur/$slug': {
      id: '/fitur/$slug'
      path: '/fitur/$slug'
      fullPath: '/fitur/$slug'
      preLoaderRoute: typeof FiturSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/$tahun/': {
      id: '/buku/$tahun/'
      path: '/buku/$tahun'
      fullPath: '/buku/$tahun/'
      preLoaderRoute: typeof BukuTahunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/$tahun/$bab': {
      id: '/buku/$tahun/$bab'
      path: '/buku/$tahun/$bab'
      fullPath: '/buku/$tahun/$bab'
      preLoaderRoute: typeof BukuTahunBabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HasilRoute: HasilRoute,
  LembagaRoute: LembagaRoute,
  ProfilRoute: ProfilRoute,
  RoadmapRoute: RoadmapRoute,
  BukuPencarianRoute: BukuPencarianRoute,
  FiturSlugRoute: FiturSlugRoute,
  BukuIndexRoute: BukuIndexRoute,
  BukuTahunBabRoute: BukuTahunBabRoute,
  BukuTahunIndexRoute: BukuTahunIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
