/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as LembagaRouteImport } from './routes/lembaga'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as BukuIndexRouteImport } from './routes/buku.index'
import { Route as BukuPencarianRouteImport } from './routes/buku.pencarian'
import { Route as FiturSlugRouteImport } from './routes/fitur.$slug'
import { Route as GambarIndexRouteImport } from './routes/gambar.index'
import { Route as GambarSemuaRouteImport } from './routes/gambar.semua'
import { Route as HangeulIndexRouteImport } from './routes/hangeul.index'
import { Route as HangeulAngkaRouteImport } from './routes/hangeul.angka'
import { Route as HangeulMataUangRouteImport } from './routes/hangeul.mata-uang'
import { Route as HangeulSatuanRouteImport } from './routes/hangeul.satuan'
import { Route as HangeulVokalKonsonanRouteImport } from './routes/hangeul.vokal-konsonan'
import { Route as KosaKataIndexRouteImport } from './routes/kosa-kata.index'
import { Route as KosaKataAntonimRouteImport } from './routes/kosa-kata.antonim'
import { Route as KosaKataSemuaRouteImport } from './routes/kosa-kata.semua'
import { Route as KosaKataSinonimRouteImport } from './routes/kosa-kata.sinonim'
import { Route as TataBahasaIndexRouteImport } from './routes/tata-bahasa.index'
import { Route as TataBahasaSlugRouteImport } from './routes/tata-bahasa.$slug'
import { Route as UjiKemampuanIndexRouteImport } from './routes/uji-kemampuan.index'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as BukuTahunIndexRouteImport } from './routes/buku.$tahun.index'
import { Route as BukuTahunBabRouteImport } from './routes/buku.$tahun.$bab'
import { Route as UjiKemampuanTebakTebakanIndexRouteImport } from './routes/uji-kemampuan.tebak-tebakan.index'
import { Route as UjiKemampuanUbtIndexRouteImport } from './routes/uji-kemampuan.ubt.index'
import { Route as GambarBukuTahunIndexRouteImport } from './routes/gambar.buku.$tahun.index'
import { Route as GambarBukuTahunBabRouteImport } from './routes/gambar.buku.$tahun.$bab'
import { Route as KosaKataBukuTahunIndexRouteImport } from './routes/kosa-kata.buku.$tahun.index'
import { Route as KosaKataBukuTahunBabRouteImport } from './routes/kosa-kata.buku.$tahun.$bab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const LembagaRoute = LembagaRouteImport.update({
  id: '/lembaga',
  path: '/lembaga',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuIndexRoute = BukuIndexRouteImport.update({
  id: '/buku/',
  path: '/buku/',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuPencarianRoute = BukuPencarianRouteImport.update({
  id: '/buku/pencarian',
  path: '/buku/pencarian',
  getParentRoute: () => rootRouteImport,
} as any)
const FiturSlugRoute = FiturSlugRouteImport.update({
  id: '/fitur/$slug',
  path: '/fitur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GambarIndexRoute = GambarIndexRouteImport.update({
  id: '/gambar/',
  path: '/gambar/',
  getParentRoute: () => rootRouteImport,
} as any)
const GambarSemuaRoute = GambarSemuaRouteImport.update({
  id: '/gambar/semua',
  path: '/gambar/semua',
  getParentRoute: () => rootRouteImport,
} as any)
const HangeulIndexRoute = HangeulIndexRouteImport.update({
  id: '/hangeul/',
  path: '/hangeul/',
  getParentRoute: () => rootRouteImport,
} as any)
const HangeulAngkaRoute = HangeulAngkaRouteImport.update({
  id: '/hangeul/angka',
  path: '/hangeul/angka',
  getParentRoute: () => rootRouteImport,
} as any)
const HangeulMataUangRoute = HangeulMataUangRouteImport.update({
  id: '/hangeul/mata-uang',
  path: '/hangeul/mata-uang',
  getParentRoute: () => rootRouteImport,
} as any)
const HangeulSatuanRoute = HangeulSatuanRouteImport.update({
  id: '/hangeul/satuan',
  path: '/hangeul/satuan',
  getParentRoute: () => rootRouteImport,
} as any)
const HangeulVokalKonsonanRoute = HangeulVokalKonsonanRouteImport.update({
  id: '/hangeul/vokal-konsonan',
  path: '/hangeul/vokal-konsonan',
  getParentRoute: () => rootRouteImport,
} as any)
const KosaKataIndexRoute = KosaKataIndexRouteImport.update({
  id: '/kosa-kata/',
  path: '/kosa-kata/',
  getParentRoute: () => rootRouteImport,
} as any)
const KosaKataAntonimRoute = KosaKataAntonimRouteImport.update({
  id: '/kosa-kata/antonim',
  path: '/kosa-kata/antonim',
  getParentRoute: () => rootRouteImport,
} as any)
const KosaKataSemuaRoute = KosaKataSemuaRouteImport.update({
  id: '/kosa-kata/semua',
  path: '/kosa-kata/semua',
  getParentRoute: () => rootRouteImport,
} as any)
const KosaKataSinonimRoute = KosaKataSinonimRouteImport.update({
  id: '/kosa-kata/sinonim',
  path: '/kosa-kata/sinonim',
  getParentRoute: () => rootRouteImport,
} as any)
const TataBahasaIndexRoute = TataBahasaIndexRouteImport.update({
  id: '/tata-bahasa/',
  path: '/tata-bahasa/',
  getParentRoute: () => rootRouteImport,
} as any)
const TataBahasaSlugRoute = TataBahasaSlugRouteImport.update({
  id: '/tata-bahasa/$slug',
  path: '/tata-bahasa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UjiKemampuanIndexRoute = UjiKemampuanIndexRouteImport.update({
  id: '/uji-kemampuan/',
  path: '/uji-kemampuan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuTahunIndexRoute = BukuTahunIndexRouteImport.update({
  id: '/buku/$tahun/',
  path: '/buku/$tahun/',
  getParentRoute: () => rootRouteImport,
} as any)
const BukuTahunBabRoute = BukuTahunBabRouteImport.update({
  id: '/buku/$tahun/$bab',
  path: '/buku/$tahun/$bab',
  getParentRoute: () => rootRouteImport,
} as any)
const UjiKemampuanTebakTebakanIndexRoute =
  UjiKemampuanTebakTebakanIndexRouteImport.update({
    id: '/uji-kemampuan/tebak-tebakan/',
    path: '/uji-kemampuan/tebak-tebakan/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UjiKemampuanUbtIndexRoute = UjiKemampuanUbtIndexRouteImport.update({
  id: '/uji-kemampuan/ubt/',
  path: '/uji-kemampuan/ubt/',
  getParentRoute: () => rootRouteImport,
} as any)
const GambarBukuTahunIndexRoute = GambarBukuTahunIndexRouteImport.update({
  id: '/gambar/buku/$tahun/',
  path: '/gambar/buku/$tahun/',
  getParentRoute: () => rootRouteImport,
} as any)
const GambarBukuTahunBabRoute = GambarBukuTahunBabRouteImport.update({
  id: '/gambar/buku/$tahun/$bab',
  path: '/gambar/buku/$tahun/$bab',
  getParentRoute: () => rootRouteImport,
} as any)
const KosaKataBukuTahunIndexRoute = KosaKataBukuTahunIndexRouteImport.update({
  id: '/kosa-kata/buku/$tahun/',
  path: '/kosa-kata/buku/$tahun/',
  getParentRoute: () => rootRouteImport,
} as any)
const KosaKataBukuTahunBabRoute = KosaKataBukuTahunBabRouteImport.update({
  id: '/kosa-kata/buku/$tahun/$bab',
  path: '/kosa-kata/buku/$tahun/$bab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/lembaga': typeof LembagaRoute
  '/profil': typeof ProfilRoute
  '/roadmap': typeof RoadmapRoute
  '/buku/pencarian': typeof BukuPencarianRoute
  '/fitur/$slug': typeof FiturSlugRoute
  '/gambar/semua': typeof GambarSemuaRoute
  '/hangeul/angka': typeof HangeulAngkaRoute
  '/hangeul/mata-uang': typeof HangeulMataUangRoute
  '/hangeul/satuan': typeof HangeulSatuanRoute
  '/hangeul/vokal-konsonan': typeof HangeulVokalKonsonanRoute
  '/kosa-kata/antonim': typeof KosaKataAntonimRoute
  '/kosa-kata/semua': typeof KosaKataSemuaRoute
  '/kosa-kata/sinonim': typeof KosaKataSinonimRoute
  '/tata-bahasa/$slug': typeof TataBahasaSlugRoute
  '/buku/': typeof BukuIndexRoute
  '/gambar/': typeof GambarIndexRoute
  '/hangeul/': typeof HangeulIndexRoute
  '/kosa-kata/': typeof KosaKataIndexRoute
  '/tata-bahasa/': typeof TataBahasaIndexRoute
  '/uji-kemampuan/': typeof UjiKemampuanIndexRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/buku/$tahun/$bab': typeof BukuTahunBabRoute
  '/buku/$tahun/': typeof BukuTahunIndexRoute
  '/uji-kemampuan/tebak-tebakan/': typeof UjiKemampuanTebakTebakanIndexRoute
  '/uji-kemampuan/ubt/': typeof UjiKemampuanUbtIndexRoute
  '/gambar/buku/$tahun/$bab': typeof GambarBukuTahunBabRoute
  '/kosa-kata/buku/$tahun/$bab': typeof KosaKataBukuTahunBabRoute
  '/gambar/buku/$tahun/': typeof GambarBukuTahunIndexRoute
  '/kosa-kata/buku/$tahun/': typeof KosaKataBukuTahunIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/lembaga': typeof LembagaRoute
  '/profil': typeof ProfilRoute
  '/roadmap': typeof RoadmapRoute
  '/buku/pencarian': typeof BukuPencarianRoute
  '/fitur/$slug': typeof FiturSlugRoute
  '/gambar/semua': typeof GambarSemuaRoute
  '/hangeul/angka': typeof HangeulAngkaRoute
  '/hangeul/mata-uang': typeof HangeulMataUangRoute
  '/hangeul/satuan': typeof HangeulSatuanRoute
  '/hangeul/vokal-konsonan': typeof HangeulVokalKonsonanRoute
  '/kosa-kata/antonim': typeof KosaKataAntonimRoute
  '/kosa-kata/semua': typeof KosaKataSemuaRoute
  '/kosa-kata/sinonim': typeof KosaKataSinonimRoute
  '/tata-bahasa/$slug': typeof TataBahasaSlugRoute
  '/buku': typeof BukuIndexRoute
  '/gambar': typeof GambarIndexRoute
  '/hangeul': typeof HangeulIndexRoute
  '/kosa-kata': typeof KosaKataIndexRoute
  '/tata-bahasa': typeof TataBahasaIndexRoute
  '/uji-kemampuan': typeof UjiKemampuanIndexRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/buku/$tahun/$bab': typeof BukuTahunBabRoute
  '/buku/$tahun': typeof BukuTahunIndexRoute
  '/uji-kemampuan/tebak-tebakan': typeof UjiKemampuanTebakTebakanIndexRoute
  '/uji-kemampuan/ubt': typeof UjiKemampuanUbtIndexRoute
  '/gambar/buku/$tahun/$bab': typeof GambarBukuTahunBabRoute
  '/kosa-kata/buku/$tahun/$bab': typeof KosaKataBukuTahunBabRoute
  '/gambar/buku/$tahun': typeof GambarBukuTahunIndexRoute
  '/kosa-kata/buku/$tahun': typeof KosaKataBukuTahunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/lembaga': typeof LembagaRoute
  '/profil': typeof ProfilRoute
  '/roadmap': typeof RoadmapRoute
  '/buku/pencarian': typeof BukuPencarianRoute
  '/fitur/$slug': typeof FiturSlugRoute
  '/gambar/semua': typeof GambarSemuaRoute
  '/hangeul/angka': typeof HangeulAngkaRoute
  '/hangeul/mata-uang': typeof HangeulMataUangRoute
  '/hangeul/satuan': typeof HangeulSatuanRoute
  '/hangeul/vokal-konsonan': typeof HangeulVokalKonsonanRoute
  '/kosa-kata/antonim': typeof KosaKataAntonimRoute
  '/kosa-kata/semua': typeof KosaKataSemuaRoute
  '/kosa-kata/sinonim': typeof KosaKataSinonimRoute
  '/tata-bahasa/$slug': typeof TataBahasaSlugRoute
  '/buku/': typeof BukuIndexRoute
  '/gambar/': typeof GambarIndexRoute
  '/hangeul/': typeof HangeulIndexRoute
  '/kosa-kata/': typeof KosaKataIndexRoute
  '/tata-bahasa/': typeof TataBahasaIndexRoute
  '/uji-kemampuan/': typeof UjiKemampuanIndexRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/buku/$tahun/$bab': typeof BukuTahunBabRoute
  '/buku/$tahun/': typeof BukuTahunIndexRoute
  '/uji-kemampuan/tebak-tebakan/': typeof UjiKemampuanTebakTebakanIndexRoute
  '/uji-kemampuan/ubt/': typeof UjiKemampuanUbtIndexRoute
  '/gambar/buku/$tahun/$bab': typeof GambarBukuTahunBabRoute
  '/kosa-kata/buku/$tahun/$bab': typeof KosaKataBukuTahunBabRoute
  '/gambar/buku/$tahun/': typeof GambarBukuTahunIndexRoute
  '/kosa-kata/buku/$tahun/': typeof KosaKataBukuTahunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hasil'
    | '/lembaga'
    | '/profil'
    | '/roadmap'
    | '/buku/pencarian'
    | '/fitur/$slug'
    | '/gambar/semua'
    | '/hangeul/angka'
    | '/hangeul/mata-uang'
    | '/hangeul/satuan'
    | '/hangeul/vokal-konsonan'
    | '/kosa-kata/antonim'
    | '/kosa-kata/semua'
    | '/kosa-kata/sinonim'
    | '/tata-bahasa/$slug'
    | '/buku/'
    | '/gambar/'
    | '/hangeul/'
    | '/kosa-kata/'
    | '/tata-bahasa/'
    | '/uji-kemampuan/'
    | '/api/public/tts'
    | '/buku/$tahun/$bab'
    | '/buku/$tahun/'
    | '/uji-kemampuan/tebak-tebakan/'
    | '/uji-kemampuan/ubt/'
    | '/gambar/buku/$tahun/$bab'
    | '/kosa-kata/buku/$tahun/$bab'
    | '/gambar/buku/$tahun/'
    | '/kosa-kata/buku/$tahun/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hasil'
    | '/lembaga'
    | '/profil'
    | '/roadmap'
    | '/buku/pencarian'
    | '/fitur/$slug'
    | '/gambar/semua'
    | '/hangeul/angka'
    | '/hangeul/mata-uang'
    | '/hangeul/satuan'
    | '/hangeul/vokal-konsonan'
    | '/kosa-kata/antonim'
    | '/kosa-kata/semua'
    | '/kosa-kata/sinonim'
    | '/tata-bahasa/$slug'
    | '/buku'
    | '/gambar'
    | '/hangeul'
    | '/kosa-kata'
    | '/tata-bahasa'
    | '/uji-kemampuan'
    | '/api/public/tts'
    | '/buku/$tahun/$bab'
    | '/buku/$tahun'
    | '/uji-kemampuan/tebak-tebakan'
    | '/uji-kemampuan/ubt'
    | '/gambar/buku/$tahun/$bab'
    | '/kosa-kata/buku/$tahun/$bab'
    | '/gambar/buku/$tahun'
    | '/kosa-kata/buku/$tahun'
  id:
    | '__root__'
    | '/'
    | '/hasil'
    | '/lembaga'
    | '/profil'
    | '/roadmap'
    | '/buku/pencarian'
    | '/fitur/$slug'
    | '/gambar/semua'
    | '/hangeul/angka'
    | '/hangeul/mata-uang'
    | '/hangeul/satuan'
    | '/hangeul/vokal-konsonan'
    | '/kosa-kata/antonim'
    | '/kosa-kata/semua'
    | '/kosa-kata/sinonim'
    | '/tata-bahasa/$slug'
    | '/buku/'
    | '/gambar/'
    | '/hangeul/'
    | '/kosa-kata/'
    | '/tata-bahasa/'
    | '/uji-kemampuan/'
    | '/api/public/tts'
    | '/buku/$tahun/$bab'
    | '/buku/$tahun/'
    | '/uji-kemampuan/tebak-tebakan/'
    | '/uji-kemampuan/ubt/'
    | '/gambar/buku/$tahun/$bab'
    | '/kosa-kata/buku/$tahun/$bab'
    | '/gambar/buku/$tahun/'
    | '/kosa-kata/buku/$tahun/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HasilRoute: typeof HasilRoute
  LembagaRoute: typeof LembagaRoute
  ProfilRoute: typeof ProfilRoute
  RoadmapRoute: typeof RoadmapRoute
  BukuPencarianRoute: typeof BukuPencarianRoute
  FiturSlugRoute: typeof FiturSlugRoute
  GambarSemuaRoute: typeof GambarSemuaRoute
  HangeulAngkaRoute: typeof HangeulAngkaRoute
  HangeulMataUangRoute: typeof HangeulMataUangRoute
  HangeulSatuanRoute: typeof HangeulSatuanRoute
  HangeulVokalKonsonanRoute: typeof HangeulVokalKonsonanRoute
  KosaKataAntonimRoute: typeof KosaKataAntonimRoute
  KosaKataSemuaRoute: typeof KosaKataSemuaRoute
  KosaKataSinonimRoute: typeof KosaKataSinonimRoute
  TataBahasaSlugRoute: typeof TataBahasaSlugRoute
  BukuIndexRoute: typeof BukuIndexRoute
  GambarIndexRoute: typeof GambarIndexRoute
  HangeulIndexRoute: typeof HangeulIndexRoute
  KosaKataIndexRoute: typeof KosaKataIndexRoute
  TataBahasaIndexRoute: typeof TataBahasaIndexRoute
  UjiKemampuanIndexRoute: typeof UjiKemampuanIndexRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  BukuTahunBabRoute: typeof BukuTahunBabRoute
  BukuTahunIndexRoute: typeof BukuTahunIndexRoute
  UjiKemampuanTebakTebakanIndexRoute: typeof UjiKemampuanTebakTebakanIndexRoute
  UjiKemampuanUbtIndexRoute: typeof UjiKemampuanUbtIndexRoute
  GambarBukuTahunBabRoute: typeof GambarBukuTahunBabRoute
  KosaKataBukuTahunBabRoute: typeof KosaKataBukuTahunBabRoute
  GambarBukuTahunIndexRoute: typeof GambarBukuTahunIndexRoute
  KosaKataBukuTahunIndexRoute: typeof KosaKataBukuTahunIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembaga': {
      id: '/lembaga'
      path: '/lembaga'
      fullPath: '/lembaga'
      preLoaderRoute: typeof LembagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/': {
      id: '/buku/'
      path: '/buku'
      fullPath: '/buku/'
      preLoaderRoute: typeof BukuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/pencarian': {
      id: '/buku/pencarian'
      path: '/buku/pencarian'
      fullPath: '/buku/pencarian'
      preLoaderRoute: typeof BukuPencarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitur/$slug': {
      id: '/fitur/$slug'
      path: '/fitur/$slug'
      fullPath: '/fitur/$slug'
      preLoaderRoute: typeof FiturSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gambar/': {
      id: '/gambar/'
      path: '/gambar'
      fullPath: '/gambar/'
      preLoaderRoute: typeof GambarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gambar/semua': {
      id: '/gambar/semua'
      path: '/gambar/semua'
      fullPath: '/gambar/semua'
      preLoaderRoute: typeof GambarSemuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangeul/': {
      id: '/hangeul/'
      path: '/hangeul'
      fullPath: '/hangeul/'
      preLoaderRoute: typeof HangeulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangeul/angka': {
      id: '/hangeul/angka'
      path: '/hangeul/angka'
      fullPath: '/hangeul/angka'
      preLoaderRoute: typeof HangeulAngkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangeul/mata-uang': {
      id: '/hangeul/mata-uang'
      path: '/hangeul/mata-uang'
      fullPath: '/hangeul/mata-uang'
      preLoaderRoute: typeof HangeulMataUangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangeul/satuan': {
      id: '/hangeul/satuan'
      path: '/hangeul/satuan'
      fullPath: '/hangeul/satuan'
      preLoaderRoute: typeof HangeulSatuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangeul/vokal-konsonan': {
      id: '/hangeul/vokal-konsonan'
      path: '/hangeul/vokal-konsonan'
      fullPath: '/hangeul/vokal-konsonan'
      preLoaderRoute: typeof HangeulVokalKonsonanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosa-kata/': {
      id: '/kosa-kata/'
      path: '/kosa-kata'
      fullPath: '/kosa-kata/'
      preLoaderRoute: typeof KosaKataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosa-kata/antonim': {
      id: '/kosa-kata/antonim'
      path: '/kosa-kata/antonim'
      fullPath: '/kosa-kata/antonim'
      preLoaderRoute: typeof KosaKataAntonimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosa-kata/semua': {
      id: '/kosa-kata/semua'
      path: '/kosa-kata/semua'
      fullPath: '/kosa-kata/semua'
      preLoaderRoute: typeof KosaKataSemuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosa-kata/sinonim': {
      id: '/kosa-kata/sinonim'
      path: '/kosa-kata/sinonim'
      fullPath: '/kosa-kata/sinonim'
      preLoaderRoute: typeof KosaKataSinonimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tata-bahasa/': {
      id: '/tata-bahasa/'
      path: '/tata-bahasa'
      fullPath: '/tata-bahasa/'
      preLoaderRoute: typeof TataBahasaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tata-bahasa/$slug': {
      id: '/tata-bahasa/$slug'
      path: '/tata-bahasa/$slug'
      fullPath: '/tata-bahasa/$slug'
      preLoaderRoute: typeof TataBahasaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uji-kemampuan/': {
      id: '/uji-kemampuan/'
      path: '/uji-kemampuan'
      fullPath: '/uji-kemampuan/'
      preLoaderRoute: typeof UjiKemampuanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/$tahun/': {
      id: '/buku/$tahun/'
      path: '/buku/$tahun'
      fullPath: '/buku/$tahun/'
      preLoaderRoute: typeof BukuTahunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buku/$tahun/$bab': {
      id: '/buku/$tahun/$bab'
      path: '/buku/$tahun/$bab'
      fullPath: '/buku/$tahun/$bab'
      preLoaderRoute: typeof BukuTahunBabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uji-kemampuan/tebak-tebakan/': {
      id: '/uji-kemampuan/tebak-tebakan/'
      path: '/uji-kemampuan/tebak-tebakan'
      fullPath: '/uji-kemampuan/tebak-tebakan/'
      preLoaderRoute: typeof UjiKemampuanTebakTebakanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uji-kemampuan/ubt/': {
      id: '/uji-kemampuan/ubt/'
      path: '/uji-kemampuan/ubt'
      fullPath: '/uji-kemampuan/ubt/'
      preLoaderRoute: typeof UjiKemampuanUbtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gambar/buku/$tahun/': {
      id: '/gambar/buku/$tahun/'
      path: '/gambar/buku/$tahun'
      fullPath: '/gambar/buku/$tahun/'
      preLoaderRoute: typeof GambarBukuTahunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gambar/buku/$tahun/$bab': {
      id: '/gambar/buku/$tahun/$bab'
      path: '/gambar/buku/$tahun/$bab'
      fullPath: '/gambar/buku/$tahun/$bab'
      preLoaderRoute: typeof GambarBukuTahunBabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosa-kata/buku/$tahun/': {
      id: '/kosa-kata/buku/$tahun/'
      path: '/kosa-kata/buku/$tahun'
      fullPath: '/kosa-kata/buku/$tahun/'
      preLoaderRoute: typeof KosaKataBukuTahunIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosa-kata/buku/$tahun/$bab': {
      id: '/kosa-kata/buku/$tahun/$bab'
      path: '/kosa-kata/buku/$tahun/$bab'
      fullPath: '/kosa-kata/buku/$tahun/$bab'
      preLoaderRoute: typeof KosaKataBukuTahunBabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HasilRoute: HasilRoute,
  LembagaRoute: LembagaRoute,
  ProfilRoute: ProfilRoute,
  RoadmapRoute: RoadmapRoute,
  BukuPencarianRoute: BukuPencarianRoute,
  FiturSlugRoute: FiturSlugRoute,
  GambarSemuaRoute: GambarSemuaRoute,
  HangeulAngkaRoute: HangeulAngkaRoute,
  HangeulMataUangRoute: HangeulMataUangRoute,
  HangeulSatuanRoute: HangeulSatuanRoute,
  HangeulVokalKonsonanRoute: HangeulVokalKonsonanRoute,
  KosaKataAntonimRoute: KosaKataAntonimRoute,
  KosaKataSemuaRoute: KosaKataSemuaRoute,
  KosaKataSinonimRoute: KosaKataSinonimRoute,
  TataBahasaSlugRoute: TataBahasaSlugRoute,
  BukuIndexRoute: BukuIndexRoute,
  GambarIndexRoute: GambarIndexRoute,
  HangeulIndexRoute: HangeulIndexRoute,
  KosaKataIndexRoute: KosaKataIndexRoute,
  TataBahasaIndexRoute: TataBahasaIndexRoute,
  UjiKemampuanIndexRoute: UjiKemampuanIndexRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  BukuTahunBabRoute: BukuTahunBabRoute,
  BukuTahunIndexRoute: BukuTahunIndexRoute,
  UjiKemampuanTebakTebakanIndexRoute: UjiKemampuanTebakTebakanIndexRoute,
  UjiKemampuanUbtIndexRoute: UjiKemampuanUbtIndexRoute,
  GambarBukuTahunBabRoute: GambarBukuTahunBabRoute,
  KosaKataBukuTahunBabRoute: KosaKataBukuTahunBabRoute,
  GambarBukuTahunIndexRoute: GambarBukuTahunIndexRoute,
  KosaKataBukuTahunIndexRoute: KosaKataBukuTahunIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
